# This file is a template, and might need editing before it works on your project.
# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
image: "python:3.7" 
#commands to run in the Docker container before starting each job.
before_script:
  - python --version
  - pip install -r requirements.txt
  
# different stages in the pipeline
stages:
  - Test
  - Deploy
  
#defines the job in Test Stage
pytest:
  stage: Test
  script:
  - cd src/test
  - py.test
  
#defines the job in Deploy Stage (use runner tag name)
MSDeploy:
  stage: Deploy
  script:
  - cd src/
  - pip install pyinstaller
  - pip install -r requirements.txt
  - pyinstaller -F main.py
  tags:
  - DeployTubesRPL
  artifacts:
    paths:
      - src/dist/*.exe