# This file is a template, and might need editing before it works on your project.
# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
image: "python:3.7" 
#commands to run in the Docker container before starting each job.
before_script:
  - python --version
  - pip install -r requirements.txt
  
# different stages in the pipeline
stages:
  - Static Analysis
  - Test
  - Deploy
  
#defines the job in Static Analysis Stage
pylint:
  stage: Static Analysis
  script:
  - cd src
  - pylint -d C0301 util\mysql_controller.py
  - pylint -d C0301 main.py
  - pylint -d C0301 resource.py
  - pylint -d C0301 etc\populate_db.py
  - pylint -d C0301 page\admin\header.py
  - pylint -d C0301 page\admin\index.py
  - pylint -d C0301 page\dosen\dosen_dashboard.py
  - pylint -d C0301 page\dosen\dosen_page.py
  - pylint -d C0301 page\login\forgot_password_page.py
  - pylint -d C0301 page\login\login_page.py
  - pylint -d C0301 page\mahasiswa\mahasiswa_dashboard.py
  - pylint -d C0301 page\mahasiswa\mahasiswa_page.py
  - pylint -d C0301 ui\login_page.py
  - pylint -d C0301 util\csv_reader.py
  - pylint -d C0301 util\mysql_controller.py
  - cd ..


  
#defines the job in Test Stage
pytest:
  stage: Test
  script:
  - cd test/;pytest -v
  
#defines the job in Deploy Stage (use runner tag name)
MSDeploy:
  stage: Deploy
  script:
  - cd src/
  - pip install pyinstaller
  - pip install -r requirements.txt
  - pyinstaller -F main.py
  tags:
  - DeployTubesRPL
  artifacts:
    paths:
      - src/dist/*.exe